# Introduction: All containers are on the same network. We would like to separate them to different networks.
# Instruction: Next, Associate all containers with back-end network and the vote and result app with both front-end and back-end networks.
# ------------------------------
#           BEFORE
# ------------------------------
#version: '3'
#services:
#  redis:
#    image: redis
#
#  db:
#    image: postgres:9.4
#
#  vote:
#    image: voting-app
#    ports:
#      - "5000:80"
#
#  result:
#    image: result-app
#    ports:
#        - 5001:80
#
#  worker:
#    image: worker-app
#
#networks:
#    front-end:
#      driver: bridge
#    back-end:
#      driver: bridge


# ------------------------------
#           AFTER
# ------------------------------

version: '3'
services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
        - back-end

  vote:
    image: voting-app
    ports:
      - "5000:80"
    networks:
        - front-end
        - back-end


  result:
    image: result-app
    ports:
        - 5001:80
    networks:
        - front-end
        - back-end


  worker:
    image: worker-app
    networks:
        - back-end

networks:
    front-end:
      driver: bridge
    back-end:
      driver: bridge